# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Hệ Thống Điểm Danh Qr\fontend\fontend_Lecturer\Gui\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(407, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_login = QtWidgets.QFrame(self.centralwidget)
        self.frame_login.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_login.setStyleSheet("QLabel {\n"
"    background-color: #2196F3;\n"
"    color: white;\n"
"    padding: 4px 8px;\n"
"    border-radius: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"")
        self.frame_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_login.setObjectName("frame_login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_login)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_login)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_login)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_User = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_User.setMinimumSize(QtCore.QSize(250, 35))
        self.lineEdit_User.setStatusTip("")
        self.lineEdit_User.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    background: #f7f7f7;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0078ff;\n"
"    background: white;\n"
"}\n"
"")
        self.lineEdit_User.setText("")
        self.lineEdit_User.setFrame(True)
        self.lineEdit_User.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_User.setObjectName("lineEdit_User")
        self.verticalLayout_4.addWidget(self.lineEdit_User)
        self.lineEdit_Pass = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Pass.setMinimumSize(QtCore.QSize(250, 35))
        self.lineEdit_Pass.setStatusTip("")
        self.lineEdit_Pass.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #cccccc;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"    background: #f7f7f7;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #0078ff;\n"
"    background: white;\n"
"}\n"
"")
        self.lineEdit_Pass.setInputMask("")
        self.lineEdit_Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_Pass.setObjectName("lineEdit_Pass")
        self.verticalLayout_4.addWidget(self.lineEdit_Pass)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(150, 50))
        self.frame_3.setStyleSheet("QPushButton {\n"
"    background-color: #2196F3;   /* Màu xanh */\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #42A5F5;   /* Hover sáng hơn */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1E88E5;   /* Khi nhấn tối lại */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #90CAF9;\n"
"    color: #E3E3E3;\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_Signin = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_Signin.setObjectName("pushButton_Signin")
        self.verticalLayout_5.addWidget(self.pushButton_Signin)
        self.verticalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Sign In</span></p></body></html>"))
        self.lineEdit_User.setPlaceholderText(_translate("MainWindow", "Usename"))
        self.lineEdit_Pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton_Signin.setText(_translate("MainWindow", "Sign in"))
